# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QuickOrangeLive' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for QuickOrangeLive

  pod 'Masonry'
  pod 'YYModel'
  pod 'SDWebImage'
  pod 'AFNetworking'
  pod 'FMDB'
  pod 'MJRefresh'
  

end
